// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Le moteur de migration Prisma (Rust) ne supporte pas libsql://
// → toujours utiliser SQLite local pour les commandes Prisma CLI
// → la connexion Turso est gérée par src/lib/prisma.ts à runtime
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
